### ISSUE TITLE
seedsの作成でエラー

### ISSUE THREAD

**Issue by nakajima97** [yudai-nakajima/rails-tutorial-2021#3]
# 概要
Chapter10でユーザを100名作成するコードがある
そこでArgument Errorが発生するが、原因が特定できなかった

備忘録としてissesを作成

# 終了条件
- [x] rails db:seed を問題なく実行できるようにする

# 発生状況
## コード
```Rails
# メインのサンプルユーザーを1人作成する
# create! ユーザが作成できなった場合に例外を発生させる
User.create!(
  name: "Example User",
  email: "example@railstutorial.org",
  password: "foobar",
  password_confirmation: "foobar"
)

# argument errorが発生したが原因不明。放置する。
# 追加のユーザーをまとめて生成する
99.times do |n|
  name = Faker::Name.name
  email = "example-#{n + 1}@railstutorial.org"
  password = "password"
  User.create!(
    name: name,
    email: email,
    password: password,
    password_confirmation: password
  )
end
```
## エラー全文
```
rails db:seed --trace
** Invoke db:seed (first_time)
** Invoke db:load_config (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute db:load_config
** Execute db:seed
** Invoke db:abort_if_pending_migrations (first_time)
** Invoke db:load_config 
** Execute db:abort_if_pending_migrations
rails aborted!
ArgumentError: wrong number of arguments (given 2, expected 0..1)
/usr/local/bundle/gems/i18n-1.8.10/lib/i18n.rb:196:in `translate'
/usr/local/bundle/gems/faker-2.1.2/lib/faker.rb:155:in `translate'
/usr/local/bundle/gems/faker-2.1.2/lib/faker.rb:98:in `fetch'
/usr/local/bundle/gems/faker-2.1.2/lib/faker.rb:122:in `parse'
/usr/local/bundle/gems/faker-2.1.2/lib/faker/default/name.rb:9:in `name'
/workspaces/rails-tutorial/environment/sample_app/db/seeds.rb:12:in `block in <main>'
/workspaces/rails-tutorial/environment/sample_app/db/seeds.rb:11:in `times'
/workspaces/rails-tutorial/environment/sample_app/db/seeds.rb:11:in `<main>'
/usr/local/bundle/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:59:in `load'
/usr/local/bundle/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:59:in `load'
/usr/local/bundle/gems/railties-6.1.3.2/lib/rails/engine.rb:566:in `block in load_seed'
/usr/local/bundle/gems/activesupport-6.1.3.2/lib/active_support/callbacks.rb:117:in `block in run_callbacks'
/usr/local/bundle/gems/activesupport-6.1.3.2/lib/active_support/execution_wrapper.rb:88:in `wrap'
/usr/local/bundle/gems/railties-6.1.3.2/lib/rails/engine.rb:640:in `block (2 levels) in <class:Engine>'
/usr/local/bundle/gems/activesupport-6.1.3.2/lib/active_support/callbacks.rb:126:in `instance_exec'
/usr/local/bundle/gems/activesupport-6.1.3.2/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
/usr/local/bundle/gems/activesupport-6.1.3.2/lib/active_support/callbacks.rb:137:in `run_callbacks'
/usr/local/bundle/gems/railties-6.1.3.2/lib/rails/engine.rb:566:in `load_seed'
/usr/local/bundle/gems/activerecord-6.1.3.2/lib/active_record/tasks/database_tasks.rb:450:in `load_seed'
/usr/local/bundle/gems/activerecord-6.1.3.2/lib/active_record/railties/databases.rake:392:in `block (2 levels) in <main>'
/usr/local/lib/ruby/gems/3.0.0/gems/rake-13.0.3/lib/rake/task.rb:281:in `block in execute'
/usr/local/lib/ruby/gems/3.0.0/gems/rake-13.0.3/lib/rake/task.rb:281:in `each'
/usr/local/lib/ruby/gems/3.0.0/gems/rake-13.0.3/lib/rake/task.rb:281:in `execute'
/usr/local/lib/ruby/gems/3.0.0/gems/rake-13.0.3/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
/usr/local/lib/ruby/gems/3.0.0/gems/rake-13.0.3/lib/rake/task.rb:199:in `synchronize'
/usr/local/lib/ruby/gems/3.0.0/gems/rake-13.0.3/lib/rake/task.rb:199:in `invoke_with_call_chain'
/usr/local/lib/ruby/gems/3.0.0/gems/rake-13.0.3/lib/rake/task.rb:188:in `invoke'
/usr/local/lib/ruby/gems/3.0.0/gems/rake-13.0.3/lib/rake/application.rb:160:in `invoke_task'
/usr/local/lib/ruby/gems/3.0.0/gems/rake-13.0.3/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/usr/local/lib/ruby/gems/3.0.0/gems/rake-13.0.3/lib/rake/application.rb:116:in `each'
/usr/local/lib/ruby/gems/3.0.0/gems/rake-13.0.3/lib/rake/application.rb:116:in `block in top_level'
/usr/local/lib/ruby/gems/3.0.0/gems/rake-13.0.3/lib/rake/application.rb:125:in `run_with_threads'
/usr/local/lib/ruby/gems/3.0.0/gems/rake-13.0.3/lib/rake/application.rb:110:in `top_level'
/usr/local/bundle/gems/railties-6.1.3.2/lib/rails/commands/rake/rake_command.rb:24:in `block (2 levels) in perform'
/usr/local/lib/ruby/gems/3.0.0/gems/rake-13.0.3/lib/rake/application.rb:186:in `standard_exception_handling'
/usr/local/bundle/gems/railties-6.1.3.2/lib/rails/commands/rake/rake_command.rb:24:in `block in perform'
/usr/local/lib/ruby/gems/3.0.0/gems/rake-13.0.3/lib/rake/rake_module.rb:59:in `with_application'
/usr/local/bundle/gems/railties-6.1.3.2/lib/rails/commands/rake/rake_command.rb:18:in `perform'
/usr/local/bundle/gems/railties-6.1.3.2/lib/rails/command.rb:52:in `invoke'
/usr/local/bundle/gems/railties-6.1.3.2/lib/rails/commands.rb:18:in `<main>'
/usr/local/bundle/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/usr/local/bundle/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/usr/local/bundle/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/usr/local/bundle/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/usr/local/bundle/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/workspaces/rails-tutorial/environment/sample_app/bin/rails:5:in `<top (required)>'
/usr/local/bundle/gems/spring-2.1.1/lib/spring/client/rails.rb:28:in `load'
/usr/local/bundle/gems/spring-2.1.1/lib/spring/client/rails.rb:28:in `call'
/usr/local/bundle/gems/spring-2.1.1/lib/spring/client/command.rb:7:in `call'
/usr/local/bundle/gems/spring-2.1.1/lib/spring/client.rb:30:in `run'
/usr/local/bundle/gems/spring-2.1.1/bin/spring:49:in `<top (required)>'
/usr/local/bundle/gems/spring-2.1.1/lib/spring/binstub.rb:11:in `load'
/usr/local/bundle/gems/spring-2.1.1/lib/spring/binstub.rb:11:in `<top (required)>'
<internal:/usr/local/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
<internal:/usr/local/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
/workspaces/rails-tutorial/environment/sample_app/bin/spring:10:in `block in <top (required)>'
<internal:kernel>:90:in `tap'
/workspaces/rails-tutorial/environment/sample_app/bin/spring:7:in `<top (required)>'
bin/rails:2:in `load'
bin/rails:2:in `<main>'
Tasks: TOP => db:seed
```

# 解決策
fakerをupdateしたら正常に動作した
`bundle update faker`

**Comment by nakajima97** [comment]
終了条件を達成したためクローズ
