### ISSUE TITLE
second - paginateのtestでfaildになる

### ISSUE THREAD

**Issue by nakajima97** [yudai-nakajima/rails-tutorial-2021#7]
# 概要
`リスト 10.48:ページネーションを含めたUsersIndexのテスト green`のテストコードが失敗する

# 終了条件
- [x] テストを動作するようにする

# 事象
```bash
 FAIL UsersIndexTest#test_index_including_pagination (0.82s)
        Expected at least 1 element matching "a[href="/users/14035331"]", found 0..
        Expected 0 to be >= 1.
        test/integration/users_index_test.rb:15:in `block (2 levels) in <class:UsersIndexTest>'
        test/integration/users_index_test.rb:14:in `block in <class:UsersIndexTest>'
```

**Comment by nakajima97** [comment]
viewのタイプミスが原因でした
